name: C++ CI (Windows)

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

permissions:
  checks: write
  pull-requests: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgGitCommitId: 'latest'
          runVcpkgInstall: true

      - name: Configure CMake
        run: |
          mkdir build
          cd build
          cmake -G "Ninja" -DCMAKE_BUILD_TYPE=Debug -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}\vcpkg\scripts\buildsystems\vcpkg.cmake ..

      - name: Build the project
        run: |
          cd build
          cmake --build .

      - name: Run tests
        run: |
          cd build
          ctest --output-on-failure --C Debug

      - name: Generate code coverage report
        run: |
          cd build
          lcov --capture --directory . --output-file coverage.info
          lcov --remove coverage.info 'C:/Program Files/*' --output-file coverage.info
          lcov --list coverage.info

      - name: Upload code coverage report to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: build/coverage.info
          flags: unittests
          name: C++ CI Coverage
          fail_ci_if_error: false
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: "build/test-results.xml"
        continue-on-error: true

      - name: Upload Artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: CellViz
          path: ./build/CellViz.exe
          retention-days: 5
          continue-on-error: true
