name: C++ CI

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies (CMake)
        run: |
          sudo apt-get update
          sudo apt-get install cmake g++ libboost-all-dev

      - name: Build the project
        run: |
          mkdir build
          cd build
          cmake ..
          make

      - name: Run tests
        run: ./build/runTests
